### ISSUE TITLE
Developing Theme

### ISSUE THREAD

**Issue by DursunCanPoyraz** [yannisme/flarum-oxo-theme#1]
I don't know coding. I can only offer suggestions. I can report bugs.

**1-**

![image](https://user-images.githubusercontent.com/74768208/143669858-e88a8cd7-8e65-42da-8dc8-279d625b37da.png)

**2-**

The borders on the blog page can be made round.

**3-**

Mobile compatibility can be added.

**Comment by yannisme** [comment]
I can't test the first question, do u have any demo site to show me ?
![1111](https://user-images.githubusercontent.com/20273789/143673174-c3573863-7928-42ee-9cd6-702ca199d206.png)

the second and third are OK in the next v2.0.2 .

**Comment by DursunCanPoyraz** [comment]
`https://durpoy.com`

**Comment by yannisme** [comment]
Maybe it is ok now, please update to v2.0.4~
the Ext.`blog` mobile compatibility will be added in v2.0.5

**Comment by DursunCanPoyraz** [comment]
**1-**
`https://durpoy.com/blog/2-cloudflare-err-connection-refused-cozumu`

![image](https://user-images.githubusercontent.com/74768208/143675263-cdd9270f-63e2-4d6e-bdca-d676c4385047.png)

**2-**
same

![image](https://user-images.githubusercontent.com/74768208/143675301-583848f6-9569-4222-a358-edceb823b201.png)

**Comment by yannisme** [comment]
Check out the cache and try again XD

**Comment by DursunCanPoyraz** [comment]
Can you sign up for the site and give it a try? I am still the same. _I opened the registration. There is an e-mail confirmation._

**Comment by DursunCanPoyraz** [comment]
The header in the blog article is fine. Other links are broken. Sample pictures:

![image](https://user-images.githubusercontent.com/74768208/143675597-40eff661-f7b7-41c3-b7ac-5782ecae544c.png)
![image](https://user-images.githubusercontent.com/74768208/143675603-dd15b6ae-0c85-4e88-bd16-063ad3e8412d.png)
![image](https://user-images.githubusercontent.com/74768208/143675615-5fb62dd5-1518-450a-ba41-cec1ee672102.png)

**Comment by yannisme** [comment]
please add these code, and F5 try again：

```
span.Avatar {
    display: inline-flex!important;
}
```

**Comment by yannisme** [comment]
please update to v2.0.5 to fix this problem~ 🤣

**Comment by DursunCanPoyraz** [comment]
Fixed.
I can't develop the theme myself because I don't know coding. Can you do if I have any other suggestions? (if the suggestions are simple)

**Comment by yannisme** [comment]
Its OK 😘

**Comment by DursunCanPoyraz** [comment]
Can you add compatibility to the theme for widget extensions? You have a membership on the site. You can try.

![image](https://user-images.githubusercontent.com/74768208/143846188-74c88290-aa86-4d13-8fa7-6aa4a5e438d8.png)

**Comment by DursunCanPoyraz** [comment]
![image](https://user-images.githubusercontent.com/74768208/143857736-ed1b9a5d-bdcb-405f-a0f7-9ba41a19dc62.png)

**Comment by yannisme** [comment]
OK，fixed it
![1212](https://user-images.githubusercontent.com/20273789/143876577-626fc212-d750-4185-8b0b-d8cd580d0df5.png)

**Comment by DursunCanPoyraz** [comment]
Can we separate the tags and the top menu? It may be a different design.

![image](https://user-images.githubusercontent.com/74768208/143908914-2d6ebf79-4877-4a95-9579-1aa3cf2e985c.png)

**Comment by DursunCanPoyraz** [comment]
Can you add compatibility to the Last Registered Users extension?

https://discuss.flarum.org/d/28923-last-registered-users-widget 

![image](https://user-images.githubusercontent.com/74768208/143931406-c1b10688-64e8-46e6-805a-50c9b3fca8f7.png)

**Comment by yannisme** [comment]
Icannot separate the tags and the top menu~ the latest one is OK in v2.0.7

**Comment by DursunCanPoyraz** [comment]
![image](https://user-images.githubusercontent.com/74768208/144086513-9b830c65-df6f-4807-903e-3063f923fbc4.png)

**Comment by yannisme** [comment]
update to v2.0.7

**Comment by yannisme** [comment]
![image](https://user-images.githubusercontent.com/20273789/144405258-aea94689-186a-4731-93bd-0376d1312ef9.png)

I will update with other bugs later, the rendering is shown in the figure~

**Comment by yannisme** [comment]
I will close this issue.

- Support for sidebar extension `last-registered-users-widget` separately
- Targeted optimization of all tab pages
- Support the Ext.`blog` on mobile
- Fixed some bugs
```
composer update yannisme/oxotheme
php flarum cache:clear
```
![1212](https://user-images.githubusercontent.com/20273789/144427697-2001533e-2015-416f-9f88-807dc3b7cfdc.png)
![1213](https://user-images.githubusercontent.com/20273789/144427700-90aa0186-b802-40f9-a514-26bde2dd2134.png)
![1111](https://user-images.githubusercontent.com/20273789/144427691-6d141925-a933-4aa5-8d3e-fa8b11ca4f39.png)
