### ISSUE TITLE
GTmetrix values

### ISSUE THREAD

**Issue by DursunCanPoyraz** [yannisme/flarum-oxo-theme#2]
Does theme affect GTmetrix site values? Because I have very few extensions installed on my site, including the theme.

https://gtmetrix.com/reports/durpoy.com/WuJhxvCy/

**Comment by yannisme** [comment]
Nope, this theme just use css/less file to modify pages, no more js file to load, so dont worry to use my all theme. 😺
Of course, you can also try uninstalling or disabling the theme and test it again. 😊
