### ISSUE TITLE
Hot Cards extension compatibility

### ISSUE THREAD

**Issue by DursunCanPoyraz** [yannisme/flarum-oxo-theme#3]
Can you make this extension compatible? There are too many blank lines.

https://discuss.flarum.org/d/29767-popular-discussion-cards

![image](https://user-images.githubusercontent.com/74768208/147824068-0277297b-4eb0-442c-8949-7e43194d1c0e.png)

**Comment by yannisme** [comment]
OK, LET ME SEE~

**Comment by yannisme** [comment]
Version 2.1.1 completed！
I have been busy recently, so sry XP
