### ISSUE TITLE
开启fof/best-answer插件后，文字框下移

### ISSUE THREAD

**Issue by Clamours** [yannisme/flarum-oxo-theme#5]
首先感谢作者，这个主题真的很漂亮。但是我在这里遇到了一个问题：
开启fof/best-answer插件后，每个post的显示位置下降了很多，所有的post都会这样(无论是不是问答帖)，关闭fof/best-answer马上就没有问题了，所以我想这应该是与fof/best-answer不兼容
![WX20230916-160003@2x](https://github.com/yannisme/flarum-oxo-theme/assets/60908461/be3dabf4-bfd0-436a-bee4-eae9f9c9f4a7)
![WX20230916-155849@2x](https://github.com/yannisme/flarum-oxo-theme/assets/60908461/68501501-5e15-4f7f-b64b-a69130851787)

**Comment by yannisme** [comment]
OK,明天我看看

**Comment by Clamours** [comment]
感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yannisme/flarum-oxo-theme"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月16日(星期六) 晚上9:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yannisme/flarum-oxo-theme] 开启fof/best-answer插件后，文字框下移 (Issue #5)





 
OK,明天我看看

**Comment by Clamours** [comment]
不好意思，忘记回复了。这个问题我已经通过如下一段CSS完美解决了！

/* 去除留白区域 */
@media (min-width: 992px) {
  .Post-header>ul {
    height: 15px;
  }
}
